const checkoutController = require('../../controllers/client/checkout-controller');
const checkoutValidate = require('../../validates/client/checkout-validate');
const express = require('express');
const router = express.Router();
router.get('/', checkoutController.checkout);
router.post('/cash', checkoutValidate.checkout, checkoutController.checkoutCash);
router.post('/vnpay', checkoutValidate.checkout, checkoutController.checkoutVnpay);
router.get('/vnpay_return', checkoutController.vnpayReturn);
router.get("/success/:id", checkoutController.success);
module.exports = router;