const productRouter = require('./product-route')
const homeRouter = require('./home-route')
const searchRouter = require('./search-route')
const cartRouter = require('./cart-route')
const checkoutRouter = require('./checkout-route')
const userRouter = require('./user-route')
const orderRouter = require('./order-route')
const blogRouter = require('./blog-route')
const ProductCategoryMiddleware = require('../../middleware/client/product-category-middleware')
const cartMiddleware = require('../../middleware/client/cart-middleware')
const userMiddleware = require('../../middleware/client/user-middleware')
const websiteInfor = require('../../middleware/client/website-infor')
module.exports = (app)=>{{
    app.use(websiteInfor)
    app.use(ProductCategoryMiddleware.category)
    app.use(userMiddleware.checkLogin)
    app.use(cartMiddleware.cart)
    app.use("/",homeRouter)
    app.use("/products",productRouter)
    app.use('/search',searchRouter)
    app.use('/cart',cartRouter)
    app.use('/checkout',checkoutRouter)
    app.use('/user',userRouter)
    app.use('/orders',orderRouter)
    app.use('/blog',blogRouter)
}}