const userController = require('../../controllers/client/user-controller');
const userValidate = require('../../validates/client/user-validate');
const mongoose = require('mongoose');
const router = require('express').Router();
router.get('/register', userController.register);
router.post('/register', userValidate.register, userController.registerPost);
router.get('/login', userController.login);
router.post('/login', userValidate.login, userController.loginPost);
router.post('/logout', userController.logout);
router.get('/password/forgot', userController.forgotPassword);
router.post('/password/forgot', userValidate.forgotPassword, userController.forgotPasswordPost);
router.get('/password/otp', userController.otp);
router.post('/password/otp', userValidate.otp, userController.otpPost);
router.get('/password/reset-password', userController.resetPassword);
router.post('/password/reset-password', userValidate.resetPassword, userController.resetPasswordPost);
module.exports = router;